# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a39b72165d1c0ea3fc5a729cded7b458f5c76547ac161211b33f4fee709031943cb1c24563963282707a33ee90b101d4d3b2cf5ecb7c534c545b8c5788dd3071

test:
  secret_key_base: 146a15facc6478b88b843a92e5e7459efc60491937111550d7feea578f7038e97c997c7b1c8994006d78632ad3963e0a4b84cd3537d7fbef644eaf346516e781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
