require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExtrasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Extra. As you add validations to Extra, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExtrasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all extras as @extras" do
      extra = Extra.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:extras)).to eq([extra])
    end
  end

  describe "GET show" do
    it "assigns the requested extra as @extra" do
      extra = Extra.create! valid_attributes
      get :show, {:id => extra.to_param}, valid_session
      expect(assigns(:extra)).to eq(extra)
    end
  end

  describe "GET new" do
    it "assigns a new extra as @extra" do
      get :new, {}, valid_session
      expect(assigns(:extra)).to be_a_new(Extra)
    end
  end

  describe "GET edit" do
    it "assigns the requested extra as @extra" do
      extra = Extra.create! valid_attributes
      get :edit, {:id => extra.to_param}, valid_session
      expect(assigns(:extra)).to eq(extra)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Extra" do
        expect {
          post :create, {:extra => valid_attributes}, valid_session
        }.to change(Extra, :count).by(1)
      end

      it "assigns a newly created extra as @extra" do
        post :create, {:extra => valid_attributes}, valid_session
        expect(assigns(:extra)).to be_a(Extra)
        expect(assigns(:extra)).to be_persisted
      end

      it "redirects to the created extra" do
        post :create, {:extra => valid_attributes}, valid_session
        expect(response).to redirect_to(Extra.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved extra as @extra" do
        post :create, {:extra => invalid_attributes}, valid_session
        expect(assigns(:extra)).to be_a_new(Extra)
      end

      it "re-renders the 'new' template" do
        post :create, {:extra => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested extra" do
        extra = Extra.create! valid_attributes
        put :update, {:id => extra.to_param, :extra => new_attributes}, valid_session
        extra.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested extra as @extra" do
        extra = Extra.create! valid_attributes
        put :update, {:id => extra.to_param, :extra => valid_attributes}, valid_session
        expect(assigns(:extra)).to eq(extra)
      end

      it "redirects to the extra" do
        extra = Extra.create! valid_attributes
        put :update, {:id => extra.to_param, :extra => valid_attributes}, valid_session
        expect(response).to redirect_to(extra)
      end
    end

    describe "with invalid params" do
      it "assigns the extra as @extra" do
        extra = Extra.create! valid_attributes
        put :update, {:id => extra.to_param, :extra => invalid_attributes}, valid_session
        expect(assigns(:extra)).to eq(extra)
      end

      it "re-renders the 'edit' template" do
        extra = Extra.create! valid_attributes
        put :update, {:id => extra.to_param, :extra => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested extra" do
      extra = Extra.create! valid_attributes
      expect {
        delete :destroy, {:id => extra.to_param}, valid_session
      }.to change(Extra, :count).by(-1)
    end

    it "redirects to the extras list" do
      extra = Extra.create! valid_attributes
      delete :destroy, {:id => extra.to_param}, valid_session
      expect(response).to redirect_to(extras_url)
    end
  end

end
